# Generated by Django 2.0.1 on 2018-01-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAmericaAssignedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_group', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaCategoryProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=120)),
                ('engineer_last_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaReasonForCreatingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_ticket', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaStatusTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ticket', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaTriageCategoryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaTriageSubcategoryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_subcategory', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CentralAmericaVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaCategoryProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=120)),
                ('engineer_last_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaPriorityTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_priority', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaReasonForCreatingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaRNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaStatusTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaTriageCategoryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaTriageSubCategoryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_subcategory', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ColombiaVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=120)),
            ],
        ),
    ]
