# Generated by Django 2.0.1 on 2018-01-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_navigator', '0002_delete_colombiarnc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColombiaRegion',
        ),
    ]
