# Generated by Django 2.0.1 on 2018-03-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_navigator', '0003_delete_colombiaregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameModel(
            old_name='CentralAmericaAssignedGroup',
            new_name='SecurityAuditAffectedDevicesCategory',
        ),
        migrations.RenameModel(
            old_name='CentralAmericaEngineer',
            new_name='SecurityAuditEngineer',
        ),
        migrations.RenameModel(
            old_name='ColombiaReasonForCreatingTicket',
            new_name='SecurityAuditPriorityTicket',
        ),
        migrations.RenameModel(
            old_name='ColombiaTriageSubCategoryTicket',
            new_name='SecurityAuditProblemCategory',
        ),
        migrations.RenameModel(
            old_name='ColombiaStatusTicket',
            new_name='SecurityAuditReasonForCreatingTicket',
        ),
        migrations.RenameModel(
            old_name='ColombiaTech',
            new_name='SecurityAuditStatusTicket',
        ),
        migrations.RenameModel(
            old_name='ColombiaVendor',
            new_name='SecurityAuditVendor',
        ),
        migrations.DeleteModel(
            name='CentralAmericaCategoryProblem',
        ),
        migrations.DeleteModel(
            name='CentralAmericaMarket',
        ),
        migrations.DeleteModel(
            name='CentralAmericaReasonForCreatingTicket',
        ),
        migrations.DeleteModel(
            name='CentralAmericaStatusTicket',
        ),
        migrations.DeleteModel(
            name='CentralAmericaTech',
        ),
        migrations.DeleteModel(
            name='CentralAmericaTriageCategoryTicket',
        ),
        migrations.DeleteModel(
            name='CentralAmericaTriageSubcategoryTicket',
        ),
        migrations.DeleteModel(
            name='CentralAmericaVendor',
        ),
        migrations.DeleteModel(
            name='ColombiaCategoryProblem',
        ),
        migrations.DeleteModel(
            name='ColombiaEngineer',
        ),
        migrations.DeleteModel(
            name='ColombiaPriorityTicket',
        ),
        migrations.DeleteModel(
            name='ColombiaTriageCategoryTicket',
        ),
        migrations.RenameField(
            model_name='securityauditaffecteddevicescategory',
            old_name='assigned_group',
            new_name='affected_device_category',
        ),
        migrations.RenameField(
            model_name='securityauditpriorityticket',
            old_name='reason_category',
            new_name='ticket_priority',
        ),
        migrations.RenameField(
            model_name='securityauditproblemcategory',
            old_name='ticket_subcategory',
            new_name='problem_category',
        ),
        migrations.RenameField(
            model_name='securityauditreasonforcreatingticket',
            old_name='ticket_status',
            new_name='reason_category',
        ),
        migrations.RenameField(
            model_name='securityauditstatusticket',
            old_name='technology',
            new_name='ticket_status',
        ),
    ]
